### ISSUE TITLE
hide toolbar and change styles

### ISSUE THREAD

**Issue by ErnestoLopez** [stevermeister/ngx-wig#147]
Hi,

If I configure 

[buttons]="''"

the toolbar is minimized but still remains border.

I try to change styles through

.nw-toolbar 

selector but it does nothing

What I doing bad ?

Regards

Ernesto

**Comment by bampakoa** [comment]
@ErnestoLopez try the following style:

```css
.ng-wig .nw-toolbar{
  border: none;
}
```
